#!/bin/bash

bootsize='399' # MB
swapfile='0' # MB
timezone='Asia/Muscat'
language=(ar_OM en_US)
keymaps=(us)

packages_list() {

    PACKAGES+=(
        # micro-codes
        amd-ucode intel-ucode
        # dkms
        dkms
        # efi boot
        efibootmgr
        # utilities
        bash-completion curl syslog-ng dialog unrar unzip wget zip git
        # spell check
        aspell hspell hunspell nuspell libvoikko
        # xorg
        xorg-xwayland
        # filesystem
        lvm2 os-prober gptfdisk dosfstools mtools ntfs-3g ntfsprogs btrfs-progs xfsprogs f2fs-tools udftools
        # network
        networkmanager netctl gufw
        # wireless
        wpa_supplicant wireless_tools
        # bluetooth
        bluez bluez-utils
        # audio
        pipewire pipewire-alsa easyeffects
        # firmware
        fwupd fwupd-efi
        # trackpad
        xf86-input-synaptics
        # pacman
        archlinux-keyring
    )

    if [[ $bootloader == 'grub' ]]; then
        PACKAGES+=(
            grub grub-customizer
        )
        if grep -q btrfs /etc/fstab; then
            PACKAGES+=(
                grub-btrfs
            )
            AUR_PACKAGE+=(
                btrfs-assistant
            )
        fi
    fi

    AUR_PACKAGE+=(
        # browser
        google-chrome
    )

    if grep -q zfs /etc/fstab; then
        AUR_PACKAGE+=(
            zfs-utils zfs-dkms
        )
    fi

    if [[ $desktop == 'gnome' ]]; then

        PACKAGES+=(
            # gnome session
            gdm gnome-session gnome-shell gnome-shell-extensions gnome-control-center gnome-tweaks gnome-menus
            # gnome tools
            gnome-keyring seahorse gnome-terminal gnome-disk-utility nautilus gedit gedit-plugins gnome-system-monitor network-manager-applet
            # firmware
            gnome-firmware
        )

    fi

    if [[ $desktop == 'kde' ]]; then

        PACKAGES+=(
            # kde session
            sddm sddm-kcm plasma-desktop plasma-workspace kinit kwayland-integration kdeplasma-addons
            # system
            dolphin konsole systemsettings kde-gtk-config
            # kde tools
            kactivities kscreen kmenuedit bluedevil
            # kde theme
            kdecoration oxygen materia-kde kvantum-theme-materia
            # kde app
            discover
        )

    fi

    if [[ $computer == 'workstation' ]]; then

        if [[ $desktop == 'gnome' ]]; then
            packages+=(
                # gnome extra
                gnome-software gnome-photos gnome-music gnome-clocks gnome-contacts gnome-calculator gnome-maps gnome-logs gnome-remote-desktop gnome-screenshot gnome-boxes gnome-calendar gnome-power-manager gnome-sound-recorder gnome-font-viewer gnome-color-manager fragments gnome-subtitles gnome-connections gnome-recipes gnome-notes gnome-dictionary gnome-multi-writer gnome-bluetooth-3.0 gnome-podcasts gnome-characters gnome-code-assistance gnome-builder ghex baobab
                # gnome theme
                arc-gtk-theme arc-solid-gtk-theme arc-icon-theme materia-gtk-theme
                # photos
                gthumb eog
                # mail
                geary
                # sound
                lollypop soundconverter blanket
                # usb
                gnome-multi-writer-git
            )
            AUR_PACKAGE+=(
                # gnome extra
                gdm-settings gnome-session-properties gnome-shell-extension-dash-to-panel gnome-shell-extension-dash-to-dock gnome-shell-extension-freon gnome-text-editor
            )
        fi

        if [[ $desktop == 'kde' ]]; then
            packages+=(
                # kde app
                kmix kmail kdenlive ktorrent kdeconnect kamera kamoso okular spectacle partitionmanager akregator okteta kjots
                # photo
                kphotoalbum
                # media
                kmplayer kaffeine
                # finance
                skrooge kmymoney
                # development
                kdevelop kdevelop-php kde-dev-scripts
                # math
                cantor labplot kgraphviewer
                # edu
                kdeedu-data
                # music
                minuet
            )
            AUR_PACKAGE+=(
                # theme
                arc-kde-git
                # thumbnail
                stl-thumb-kde
                # archive
                ark-git
                # music
                amarok
                # save kde customization
                konsave
                # develop
                kdevelop-python
            )
        fi

        PACKAGES+=(
            # browser
            min
            # fonts
            font-manager woff2 awesome-terminal-fonts adobe-source-sans-fonts adobe-source-serif-fonts adobe-source-code-pro-fonts ttf-roboto ttf-ubuntu-font-family ttf-dejavu inter-font ttf-croscore
            # drawing
            drawing
            # documents
            paperwork
            # plan
            peek minder
            # stream
            obs-studio
            # vulkan
            vulkan-headers vulkan-icd-loader vulkan-validation-layers vulkan-tools
            # video
            totem celluloid pitivi
            # photos
            curtail shotwell inkscape gimp krita gmic
            # office
            libreoffice-fresh spice-up
            # pdf
            evince
            # printer
            cups cups-pdf
            # driver
            broadcom-wl-dkms
            # trackpad
            xf86-input-synaptics
            # math
            geogebra sagemath mathjax
            # wine
            wine-staging vkd3d faudio
            # finance
            homebank kresus
            # youtube
            yt-dlp
            # 3d
            blender freecad
            # 3d printer
            cura
            # code
            code stylelint
            # TypeScript
            typescript
            # tensorflow
            tensorflow tensorboard
            # mauikit
            mauikit mauikit-accounts mauikit-filebrowsing mauikit-imagetools mauikit-texteditor
            # bitcoin
            bitcoin-tx
            # playstation
            pcsx2
            # java
            jdk-openjdk
            # rust
            rust
            # php
            php php-apcu php-cgi php-phpdbg php-fpm php-geoip php-imagick php-intl php-gd php-phpdbg php-memcache php-memcached php-redis php-snmp
            # composer
            composer
            # php admin
            phpmyadmin
            # php tools
            xdebug
            # glfw
            glfw-wayland
            # android
            android-udev android-tools android-file-transfer gvfs-mtp scrcpy
            # iPhone/iPod
            ifuse
            # dependencies
            intltool
        )

        AUR_PACKAGE+=(
            # icons
            colloid-icon-theme-git
            # system restore
            timeshift
            # pdf
            acroread pdfstudioviewer
            # office
            onlyoffice-bin freeoffice wps-office openoffice-bin
            # meetings
            teams zoom
            # drives
            insync dropbox megasync-bin
            # social
            whatsapp-for-linux whatsie-git walc
            # wireless drivers
            rtl8814au-aircrack-dkms-git
            # Corsair
            ckb-next-git
            # RGB
            openrgb-git
            # screen
            green-recorder-git wayfarer-git
            # plan
            xmind
            # media player
            clapper
            # music player
            nuclear-player-bin amberol
            # video edit
            davinci-resolve video-trimmer lightworks
            # youtube
            freetube-bin youtube-music-bin
            # download
            video-downloader 4kyoutubetomp3 4kvideodownloader 4ktokkit 4kstogram
            # media
            plex-desktop
            # mail
            rambox-bin
            # android
            android-studio android-sdk android-sdk-platform-tools
            # code
            flutter swift-bin codelite-bin phpstorm webstorm webstorm-eap
            # web
            parcel-bundler
            # JavaScript
            flow-bin runjs-bin
            # javascript/css
            esbuild-bin
            # database
            dbgate-bin
            # system
            system-monitoring-center whatpulse
            # photos
            metadata-cleaner lunacy-bin annotator fastflix
            # drawing
            figma-linux-bin
            # 3d
            f3d blockbench-bin
            # map
            google-earth-pro
            # USB driver
            asekey
            # math
            wxmaxima
            # edu
            openboard lean4-bin
            # finance
            portfolio-performance-bin
            # diagram
            drawio-desktop-bin
            # stock
            jstock
            # nintendo
            yuzu-mainline-bin
            # remote
            anydesk-bin
            # gaming
            legendary
            # touch
            touchegg
            # transtation
            go-translation-git
            # nvidia optimus
            optimus-manager envycontrol
            # CPU
            corectrl
            # http
            hetty
            # netgear
            nmrpflash-bin
            # bandwidth
            peer2profit
            # USB
            ventoy-bin usbimager-bin etcher-bin
            # wine
            winegui-bin dxvk-bin
        )

    fi

    if [[ $computer == 'server' ]]; then

        PACKAGES+=(
            # SSL/TLS
            certbot
            # php
            php php-apcu php-cgi php-phpdbg php-fpm php-geoip php-imagick php-intl php-gd php-phpdbg php-memcache php-memcached php-redis php-snmp
            # php admin
            phpmyadmin
            # database
            mariadb
            # mail
            postfix postfix-mysql postfix-pcre postfixadmin dovecot dovecot-mysql opendkim cyrus-sasl
        )

        AUR_PACKAGE+=(
            # browser
            google-chrome
            # server
            openlitespeed
            # http
            hetty
        )

    fi

    if [[ $computer == 'miner' ]]; then
        AUR_PACKAGE+=(
            # browser
            google-chrome
            # miner
            trex-bin gminer-bin lolminer phoenixminer-bin teamredminer-bin
        )
    fi

}

menu() {

    echo -e "\n --> $1:\n"
    output=$2
    shift 2
    options=($@)
    i=0
    while true; do
        for option in ${options[@]}; do
            if [[ $option == ${options[$i]} ]]; then
                echo -e "\t\e[7m$option\e[0m"
            else
                echo -e "\t$option"
            fi
        done
        read -sn3 key
        if [[ $key == $(echo -en "\e[A") ]] && [[ $i -gt 0 ]]; then
            i=$(($i-1))
        elif [[ $key == $(echo -en "\e[B") ]] && [[ $i -lt ${#options[@]} ]]; then
            i=$(($i+1))
        elif [[ -z $key ]]; then
            break
        fi
        echo -en "\e[${#options[@]}A"
    done
    printf -v $output "${options[$i]}"

}

setup_drive() {

    echo "# created by Saif AlSubhi"
    echo "----------------------------------------------------------------------------------------------"
    lsblk -o name,size,mountpoint,fstype,label,model
    echo "----------------------------------------------------------------------------------------------"

    location="/dev/disk/by-id/"

    drives=($(ls $location | grep -Ew "^ata-.*|^nvme-.*|^scsi-.*|^usb-.*" | grep -v ".*-part"))

    menu "select a drive" drive ${drives[@]}

    if ls $location | grep $drive | grep part; then
        partitions=(re-partition)
        partitions+=($(ls $location | grep $drive | grep part))
        menu "select a root partition or re-partition the drive" partition ${partitions[@]}
        if ls $location | grep $partition ; then
            root_drive=$location"$partition"
            partitions=($(ls $location | grep part))
            menu "select a boot partition to mount " partition ${partitions[@]}
            boot_drive=$location"$partition"
        fi
    fi

    drive=$location"$drive"

    filesystems=(btrfs ext4 xfs zfs)
    menu "select a filesystem" filesystem ${filesystems[@]}

    bootloaders=(systemd-boot grub)
    menu "select a bootloader" bootloader ${bootloaders[@]}

    computers=(minimal miner server workstation)
    menu "select a computer" computer ${computers[@]}

    desktops=(gnome kde)
    menu "select a desktop" desktop ${desktops[@]}

    aur_installers=(makepkg aura paru pikaur yay)
    menu "select AUR installer" aur_installer ${aur_installers[@]}

    if [[ ! $root_drive ]]; then
        echo ">>> wiping filesystm"
        wipefs -a -f $drive
        echo ">>> creating GPT"
        sgdisk -o -U $drive
        echo ">>> creating boot partition"
        sgdisk -n 1:0:+"$bootsize"M -c 1:BOOT -t 1:ef00 $drive
        echo ">>> creating root partition"
        if [[ $filesystem == 'zfs' ]]; then
            sgdisk -n 2:0:0 -c 2:ROOT -t 2:bf00 $drive
        else
            sgdisk -n 2:0:0 -c 2:ROOT -t 2:8300 $drive
        fi
        boot_drive=$drive"-part1"
        root_drive=$drive"-part2"
        echo ">>> creating boot filesystem"
        sleep 1 && mkfs.fat -F32 -n BOOT $boot_drive
    fi

    echo ">>> creating root filesystem"
    if [[ $filesystem == 'zfs' ]]; then
        create_zfs
    elif [[ $filesystem == 'btrfs' ]]; then
        mkfs.btrfs -f -L ROOT $root_drive
    elif [[ $filesystem == 'ext4' ]]; then
        mkfs.ext4 -f -L ROOT $root_drive
    elif [[ $filesystem == 'xfs' ]]; then
        mkfs.xfs -f -L ROOT $root_drive
    fi

    mount_root
    mount_boot

    if [[ $filesystem == 'zfs' ]]; then
        set_zfs
    fi

    install_base

}

create_zfs() {

    echo ">>> loading ZFS modules"
    modprobe zfs
    echo ">>> checking ZFS modules"
    if ! lsmod | grep -qi zfs; then
       echo 'ERROR: ZFS modules are missing'
       create_rootfs
    fi
    echo ">>> creating ZFS pool"
    zpool create -f -o ashift=12 -o autotrim=on -O recordsize=8192 \
    -O compression=lz4 -O acltype=posixacl -O aclinherit=passthrough \
    -O devices=off -O xattr=sa -O overlay=on -O logbias=throughput \
    -O primarycache=metadata -O redundant_metadata=most \
    -O relatime=off -O atime=off -O dnodesize=legacy -O normalization=formD \
    -O canmount=on -O mountpoint=/ -R /mnt rpool $root_drive
    echo ">>> checking ZFS pool"
    zpool status
    echo ">>> setting ZFS pool as rootfs"
    zpool set bootfs=rpool rpool

}

set_zfs() {

    echo ">>> setting ZFS cache"
    zpool set cachefile=/etc/zfs/zpool.cache rpool
    mkdir -p /mnt/etc/zfs
    cp /etc/zfs/zpool.cache /mnt/etc/zfs/zpool.cache
    echo ">>> adding ZFS options"
    mkdir -p /mnt/etc/modprobe.d/
    echo "options zfs l2arc_noprefetch=0" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs l2arc_write_max=536870912" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs l2arc_write_boost=1073741824" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs l2arc_headroom=12" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options scsi_mod scan=sync" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_arc_max=536870912" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_arc_min=268435456" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_prefetch_disable=0" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_top_maxinflight=320" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_txg_timeout=15" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_scheduler=deadline" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_async_read_min_active=8" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_async_read_max_active=32" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_async_write_min_active=8" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_async_write_max_active=32" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_sync_write_min_active=8" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_sync_write_max_active=32" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_sync_read_min_active=8" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_sync_read_max_active=32" >> /mnt/etc/modprobe.d/zfs.conf

}

mount_root() {

    echo ">>> mounting root drive"
    if [[ $filesystem == 'zfs' ]]; then
        echo ">>> exporting ZFS"
        zpool export rpool
        echo ">>> importing ZFS"
        zpool import rpool -d $root_drive -R /mnt -N
        echo ">>> mounting ZFS dataset"
        zfs mount rpool
    else
        mount $root_drive /mnt
    fi

    if [[ ! -d /mnt/boot ]]; then
        mkdir -p /mnt/boot
    fi
    if [[ ! -d /mnt/boot/EFI ]]; then
        mkdir -p /mnt/boot/EFI
    fi
}

mount_boot() {

    echo ">>> mounting boot drive"
    mount $boot_drive /mnt/boot

}

update_packages() {

    if grep -Ewq "#ParallelDownloads" /etc/pacman.conf; then
        sed -i 's/\#ParallelDownloads = 5/ParallelDownloads = 10/' /etc/pacman.conf
    fi

    if grep -Ewq "#Color" /etc/pacman.conf; then
        sed -i 's/\#Color/Color/' /etc/pacman.conf
    fi

    if [[ -f /var/lib/pacman/db.lck ]]; then
        rm /var/lib/pacman/db.lck
    fi

    echo ">>> updating packages"
    pacman -Syu --needed --noconfirm

}

install_base() {

    sed -i 's/pacman_args+=(--noconfirm)/pacman_args+=(--needed --noconfirm)/' /usr/bin/pacstrap

    update_packages
    echo ">>> installing base packages"
    pacstrap /mnt base base-devel

    set_fstab

}

set_fstab() {

    echo ">>> setting fstab"
    genfstab -U -p /mnt >> /mnt/etc/fstab

    if grep -q zfs /mnt/etc/fstab; then
        sed -i 's/^rpool/#rpool/g' /mnt/etc/fstab
    fi

    sed -i 's/relatime,space_cache=v2/noatime,compress=zstd:1,ssd,discard=async/g' /mnt/etc/fstab

    echo "/EFI /boot none defaults,bind 0 0" >> /mnt/etc/fstab

    uuid=$(lsblk -dno UUID $boot_drive)
    echo $uuid > /mnt/root/chroot
    echo $computer > /mnt/root/computer
    echo $desktop > /mnt/root/desktop
    echo $aur_installer > /mnt/root/aur
    echo $bootloader > /mnt/root/bootloader
    change_root

}

change_root() {

    if [[ -f install ]]; then
        echo ">>> moving install script"
        mv install /mnt/root/install
    fi

    if mountpoint -q /mnt/sys; then
        umount -l /mnt/sys
    fi
    if mountpoint -q /mnt/dev; then
        umount -l /mnt/dev
    fi

    echo ">>> changing root"
    arch-chroot /mnt sh /root/install

}

configure() {

    set_hostname
    set_hosts
    create_user
    set_user_password
    disable_root
    set_timezone
    set_locale
    setup_desktop

}

set_hostname() {

    echo ">>> setting hostname"
    read -p " --> hostname: " HOSTNAME
    echo "$HOSTNAME" > /etc/hostname

}

set_hosts() {

    echo "127.0.0.1 localhost" > /etc/hosts
    echo "::1       localhost" >> /etc/hosts
    echo "127.0.1.1 $HOSTNAME.localdomain $HOSTNAME" >> /etc/hosts

}

create_user() {

    echo ">>> creating user"
    read -p " --> username: " USER
    if id $USER &>/dev/null; then
        userdel $USER
    fi
    useradd -m -g users -G wheel -s /bin/bash $USER || create_user
    echo "$USER ALL=(ALL) ALL" > /etc/sudoers.d/$USER

}

set_user_password() {

    echo ">>> setting user password"
    read -sp " --> $USER password: " user_password && echo ''
    read -sp " --> $USER password (confirm): " check && echo ''
    if [[ $user_password != $check ]]; then
        echo "ERROR: password did not match"
        set_user_password
    fi
    echo -en "$user_password\n$user_password" | passwd $USER

}

disable_root() {

    echo ">>> disabling root"
    passwd -l root

}

set_timezone() {

    echo ">>> setting timezone"
    if [[ -f /usr/share/zoneinfo/$timezone ]]; then
        ln -sf /usr/share/zoneinfo/$timezone /etc/localtime
        hwclock --systohc --utc
    else
        read -p " --- timezone Asia/Muscat: " timezone
        set_timezone
    fi

}

set_locale() {

    echo ">>> setting locale"
    if [[ ! $language ]]; then
        read -p " --- language en_US: " language
        set_locale
    fi
    for lang in ${language[@]}; do
        if grep -qi $lang /etc/locale.gen; then
            sed -i "s/^#$lang.UTF-8/$lang.UTF-8/" /etc/locale.gen
            localectl set-locale LANG=$lang
        fi
    done
    locale-gen

    echo "LOCALE='en_US.UTF-8'" > /etc/vconsole.conf
    echo "KEYMAP='us'" >> /etc/vconsole.conf
    for keymap in ${keymaps[@]}; do
        if localectl list-keymaps | grep -qi $keymap; then
            echo "KEYMAP_TOGGLE=$keymap" >> /etc/vconsole.conf
        fi
    done
    echo "USECOLOR='yes'" >> /etc/vconsole.conf

}

setup_desktop() {

    if ! command -v reflector; then
        echo ">>> installing reflector"
        pacman -S --needed --noconfirm rsync reflector
        echo "--save /etc/pacman.d/mirrorlist" >> /etc/xdg/reflector/reflector.conf
        echo "--country Singapore,Germany" >> /etc/xdg/reflector/reflector.conf
        echo "--protocol rsync" >> /etc/xdg/reflector/reflector.conf
        echo "--latest 5" >> /etc/xdg/reflector/reflector.conf
    fi

    install_linux

    echo ">>> packages list"
    packages_list

    if grep -q "#\[multilib\]" /etc/pacman.conf; then
        echo ">>> enabling multilib"
        sed -iz 's/\#\[multilib\]\n\#Include/\[multilib\]\nInclude/' /etc/pacman.conf
    fi

    update_packages

    install_packages

    faillock --user $USER --reset

    if [[ $aur_installer == 'makepkg' ]]; then
        install_makepkg
    elif ! command -v $aur_installer; then
        echo ">>> installing $aur_installer"
        if [[ $aur_installer == 'aura' ]]; then
            aur_installer='aura-bin'
        elif [[ $aur_installer == 'paru' ]]; then
            aur_installer='paru-bin'
        elif [[ $aur_installer == 'pikaur' ]]; then
            aur_installer='pikaur'
        elif [[ $aur_installer == 'yay' ]]; then
            aur_installer='yay-bin'
        fi
        install_aur
        install_aur_packages
    fi

    clean_packages

    enable_services

    if ! grep -qEw "custom commands" "/home/$USER/.bashrc"; then
        add_commands
    fi

    if [[ $swapfile -gt 0 ]]; then
        create_swap_file
    fi

    if [[ $bootloader == 'systemd-boot' ]]; then
        install_bootloader
    fi

    if [[ $bootloader == 'grub' ]]; then
        install_grub
    fi

    firmware_update
    set_initcpio
    finish

}

install_linux() {

    list='linux-lts linux-lts-headers linux-firmware'
    echo ">>> installing linux"
    pacman -S --needed --noconfirm $list

    echo ">>> configuring mkinitcpio"

    sed -i 's|PRESETS=(.*)|PRESETS=('default')|' /etc/mkinitcpio.d/*.preset

    if [[ -f /boot/initramfs-lts-fallback.img ]]; then
        rm /boot/initramfs-linux-lts-fallback.img
    fi

}

install_packages() {

    list=''

    for i in ${!PACKAGES[@]}; do
        list+=' '
        list+=${PACKAGES[$i]}
    done

    if grep -q btrfs /etc/fstab; then
        if [[ $bootloader == 'grub' ]]; then
            list+=' grub-btrfs'
        fi
    fi

    # intel GPU
    list+=' xf86-video-intel vulkan-intel'
    # nvidia GPU
    list+=' nvidia-open-dkms'
    # amd GPU
    list+=' xf86-video-amdgpu mesa amdvlk vulkan-radeon vulkan-mesa-layers'

    echo ">>> installing packages"
    pacman -S --needed --noconfirm $list

}

install_makepkg() {

    i=0
    for aur in ${AUR_PACKAGE[@]}; do
        i=$((i+1))
        echo ">>> AUR: $aur ($i/${#AUR_PACKAGE[@]})"
        if ! pacman -Q $aur &>/dev/null; then
            if [[ ! -d /home/$USER/$aur ]]; then
                cd /home/$USER/
                git clone https://aur.archlinux.org/$aur.git
            fi
            chown -R $USER /home/$USER/$aur
            chmod -R 770 /home/$USER/$aur
            cd /home/$USER/$aur
            sudo -u $USER makepkg -sic --needed --noconfirm --skipinteg --skippgpcheck
            rm -r /home/$USER/$aur && cd /root
            echo $aur >> /root/aurs
        fi
    done

    AURs=($(ls /home/$USER/))
    for aur in ${AURs[@]}; do
        if [[ -d /home/$USER/$aur ]]; then
            rm -r /home/$USER/$aur
        fi
    done

}

install_aur() {

    if [[ ! -d /home/$USER/$aur_installer ]]; then
        echo ">>> cloning $aur_installer"
        cd /home/$USER/
        git clone https://aur.archlinux.org/$aur_installer.git
    fi
    chown -R $USER /home/$USER/$aur_installer
    chmod -R 770 /home/$USER/$aur_installer
    cd /home/$USER/$aur_installer
    sudo -u $USER makepkg -sic --needed --noconfirm
    rm -r /home/$USER/$aur_installer && cd /root

}

install_aur_packages() {

    echo ">>> installing AUR packages"
    list=''
    for i in ${!AUR_PACKAGE[@]}; do
        list+=' '
        list+=${AUR_PACKAGE[$i]}
    done
    faillock --user $USER --reset
    if [[ $aur_installer == 'aura' ]]; then
        sudo aura -Ac --builduser=$USER --skipinteg --skippgpcheck --quiet --devel --noconfirm $list
    fi
    if [[ $aur_installer == 'paru' ]]; then
        sudo -u $USER paru -S --needed --noconfirm $list
    fi
    if [[ $aur_installer == 'pikaur' ]]; then
        sudo -u $USER pikaur -S --needed --noconfirm $list
    fi
    if [[ $aur_installer == 'yay' ]]; then
        sudo -u $USER yay -S --needed --noconfirm --batchinstall --answerclean None --answerdiff None --nocleanmenu --nodiffmenu --noeditmenu --noupgrademenu --removemake --noredownload --noprovides --norebuild --sudoloop --mflags "--needed --noconfirm" $list
    fi

}

clean_packages() {

    echo ">>> cleaning packages"
    pacman -Scc --noconfirm
    if [[ $aur_installer == 'aura' ]]; then
        sudo aura -Auac --builduser --noconfirm
    elif [[ $aur_installer == 'paru' ]]; then
        sudo -u $USER paru -Sc --noconfirm
    elif [[ $aur_installer == 'pikaur' ]]; then
        sudo -u $USER pikaur -Scc --noconfirm
    elif [[ $aur_installer == 'yay' ]]; then
        sudo -u $USER yay -Yc && sudo -u $USER yay -Scc
    fi

}

enable_services() {

    echo ">>> enabling services"

    systemctl enable NetworkManager
    systemctl enable systemd-networkd
    systemctl enable systemd-resolved
    systemctl enable ufw
    systemctl enable bluetooth
    systemctl enable reflector

    if [[ $desktop == 'gnome' ]]; then
        systemctl enable gdm
    fi

    if [[ $desktop == 'kde' ]]; then
        systemctl enable sddm
    fi

    if [[ $computer == 'workstation' ]]; then
        systemctl enable cups
    fi

    if [[ $computer == 'server' ]]; then
        systemctl enable mariadb
        systemctl enable mysql
        systemctl enable mysqld
        systemctl enable lshttpd
        systemctl enable postfix
        systemctl enable dovecot
        systemctl enable opendkim
        mkdir /var/mysql && chown -R mysql:mysql /var/mysql
        mkdir /var/log/mysql && chown -R mysql:mysql /var/log/mysql
    fi

    if grep -q zfs /etc/fstab; then
        echo ">>> enabling ZFS services"
        systemctl enable zfs-import-cache
        systemctl enable zfs-import-scan
        systemctl enable zfs-mount
        systemctl enable zfs-share
        systemctl enable zfs-zed
        systemctl enable zfs.target
    fi

}

add_commands() {

    echo ">>> adding bash aliases"
    echo "# custom commands" >> /home/$USER/.bashrc
    echo "alias install='sudo pacman -S --needed --noconfirm'" >> /home/$USER/.bashrc
    echo "alias remove='sudo pacman -R --noconfirm'" >> /home/$USER/.bashrc
    echo "alias c='clear'" >> /home/$USER/.bashrc
    echo "alias edit='SUDO_EDITOR=gedit sudoedit'" >> /home/$USER/.bashrc
    echo "alias enable='sudo systemctl enable'" >> /home/$USER/.bashrc
    echo "alias restart='sudo systemctl restart'" >> /home/$USER/.bashrc
    echo "alias status='sudo systemctl status'" >> /home/$USER/.bashrc

    echo "alis youtube='yt-dlp -o \"~/%(title)s.%(ext)s\" -f \"bv[vcodec~=\"^((he|a)vc|h26[45])\"][height<=1080][fps<=60]+ba\" --merge-output-format mp4 --downloader ffmpeg --external-downloader ffmpeg --external-downloader-args ffmpeg:\"-ss 00:00:00 -to 00:00:00\"'" >> /home/$USER/.bashrc

    if [[ $aur_installer == 'makepkg' ]]; then
        echo "alias update='sudo pacman -Syu --needed --noconfirm'" >> /home/$USER/.bashrc
        echo -e "alias aur='\ncd ~\ngit clone https://aur.archlinux.org/$2.git || cd ~/$2\ncd ~/$2\nmakepkg -sic --needed --noconfirm\nrm -r ~/$2 && cd ~\n'" >> /home/$USER/.bashrc
        echo "alias clean='sudo pacman -Scc --noconfirm && makepkg -rc --noconfirm'" >> /home/$USER/.bashrc
    fi

    if [[ $aur_installer == 'aura' ]]; then
        echo "alias update='sudo pacman -Syu --needed --noconfirm && sudo aura -Auac --devel --noconfirm'" >> /home/$USER/.bashrc
        echo "alias aur='sudo aura -Auc --needed --noconfirm'" >> /home/$USER/.bashrc
        echo "alias remove-aur='aura -R --noconfirm'" >> /home/$USER/.bashrc
        echo "alias clean='sudo pacman -Scc --noconfirm && aura -Ac --noconfirm'" >> /home/$USER/.bashrc
    fi

    if [[ $aur_installer == 'paru' ]]; then
        echo "alias update='sudo pacman -Syu --needed --noconfirm && paru -Sua --needed --noconfirm'" >> /home/$USER/.bashrc
        echo "alias aur='paru -S --needed --noconfirm'" >> /home/$USER/.bashrc
        echo "alias remove-aur='paru -R --noconfirm'" >> /home/$USER/.bashrc
        echo "alias clean='sudo pacman -Scc --noconfirm && paru -Sc --noconfirm'" >> /home/$USER/.bashrc
    fi

    if [[ $aur_installer == 'pikaur' ]]; then
        echo "alias update='sudo pacman -Syu --needed --noconfirm && pikaur -Syu'" >> /home/$USER/.bashrc
        echo "alias aur='pikaur -S --needed --noconfirm'" >> /home/$USER/.bashrc
        echo "alias remove-aur='pikaur -R --noconfirm'" >> /home/$USER/.bashrc
        echo "alias clean='sudo pacman -Scc --noconfirm && pikaur -Scc --noconfirm'" >> /home/$USER/.bashrc
    fi

    if [[ $aur_installer == 'yay' ]]; then
        echo "alias update='sudo pacman -Syu --needed --noconfirm && yay -Syu --needed --noconfirm'" >> /home/$USER/.bashrc
        echo "alias aur='yay -S --needed --noconfirm --batchinstall --answerclean None --answerdiff None --nocleanmenu --nodiffmenu --noeditmenu --noupgrademenu --removemake --noredownload --noprovides --norebuild --sudoloop --mflags \"--noconfirm\"'" >> /home/$USER/.bashrc
        echo "alias remove-aur='yay -R --noconfirm'" >> /home/$USER/.bashrc
        echo "alias clean='sudo pacman -Scc --noconfirm && yay -Yc --mflags \"--noconfirm\" && yay -Scc --mflags \"--noconfirm\"'" >> /home/$USER/.bashrc
    fi

    if [[ $computer == 'server' ]]; then
        echo "alias blacklist='sh ~/blacklist.sh'" >> /home/$USER/.bashrc
        echo "alias lsws-log='sudo rm /opt/lsws/logs/*'" >> /home/$USER/.bashrc
        echo "alias clog='sudo rm /var/log/*log*'" >> /home/$USER/.bashrc
        echo "alias mysql='mysql -u root -p'" >> /home/$USER/.bashrc
    fi

    if [[ $computer == 'miner' ]]; then
        echo "alias trex='t-rex -c ~/config.json'" >> /home/$USER/.bashrc
        echo -e "#!/bin/bash\n\nt-rex -c ~/config.json" > /etc/init.d/startup.sh
        chmod +x /etc/init.d/startup.sh
    fi

}

create_swap_file() {

    echo ">>> creating swap file"

    if grep -q zfs /etc/fstab; then
        if ! zfs get volsize rpool/swap; then
            zfs create -V "$swapfile"M -b 8192 -o compression=zle \
            -o logbias=throughput -o sync=always -o primarycache=metadata \
            -o secondarycache=none -o com.sun:auto-snapshot=false rpool/swap
            mkswap -f rpool/swap
            if ! grep -q swap /etc/fstab; then
                echo 'rpool/swap none swap discard 0 0' >> /etc/fstab
            fi
            swapon rpool/swap
        fi
    else
        if [[ ! -f /swapfile ]]; then
            truncate -s 0 /swapfile
            chattr +C /swapfile
            dd if=/dev/zero of=/swapfile bs=1M count="$swapfile"M status=progress
            chmod 600 /swapfile
            mkswap -f /swapfile
            swapon /swapfile
        fi
        if ! grep -q swapfile /etc/fstab; then
            echo '/swapfile none swap defaults 0 0' >> /etc/fstab
        fi
    fi

}

install_bootloader() {

    echo ">>> installing systemd-boot"
    bootctl --esp-path=/efi --path=/boot install

    echo ">>> configuring systemd-boot"
    sed -i 's|#timeout 3|timeout 1|' /boot/loader/loader.conf
    sed -i 's|default .*|default |' /boot/loader/loader.conf

    echo ">>> adding linux to systemd-boot"
    echo "title Arch Linux" > /boot/loader/entries/linux.conf
    echo "linux /vmlinuz-linux-lts" >> /boot/loader/entries/linux.conf
    echo "initrd /amd-ucode.img" >> /boot/loader/entries/linux.conf
    echo "initrd /intel-ucode.img" >> /boot/loader/entries/linux.conf
    echo "initrd /initramfs-linux-lts.img" >> /boot/loader/entries/linux.conf

    echo ">>> adding linux-fallback to systemd-boot"
    echo "title Arch Linux fallback" > /boot/loader/entries/linux-fallback.conf
    echo "linux /vmlinuz-linux-lts-fallback" >> /boot/loader/entries/linux-fallback.conf
    echo "initrd /amd-ucode.img" >> /boot/loader/entries/linux-fallback.conf
    echo "initrd /intel-ucode.img" >> /boot/loader/entries/linux-fallback.conf
    echo "initrd /initramfs-linux-lts-fallback.img" >> /boot/loader/entries/linux-fallback.conf

    echo ">>> adding fwupd to systemd-boot"
    ln /usr/lib/fwupd/efi/fwupdx64.efi /boot/fwupdx64.efi
    echo "title firmware update" > /boot/loader/entries/fwupd.conf
    echo "efi /fwupdx64.efi" >> /boot/loader/entries/fwupd.conf

    if [[ $filesystem == 'zfs' ]]; then
        echo "options root=zfs=rpool rw" >> /boot/loader/entries/linux.conf
        echo "options root=zfs=rpool rw" >> /boot/loader/entries/linux-fallback.conf
    else
        echo "options root=UUID=$uuid quiet architecture x64 rw" >> /boot/loader/entries/linux.conf
        echo "options root=UUID=$uuid quiet architecture x64 rw" >> /boot/loader/entries/linux-fallback.conf
    fi

    if [[ ! -f /etc/hostid ]]; then
        echo $(zgenhostid $(hostid)) > /etc/hostid
    fi

    cat <<EOF > /etc/modules-load.d/vfat.conf
vfat
nls_cp437
nls_ascii
EOF

    mkdir /etc/pacman.d/hooks
    cat <<EOF > /etc/pacman.d/hooks/99-secureboot.hook
[Trigger]
Operation = Install
Operation = Upgrade
Type = Package
Target = linux
Target = systemd

[Action]
Description = Signing Kernel for SecureBoot
When = PostTransaction
Exec = /usr/bin/find /boot -type f ( -name vmlinuz-* -o -name systemd* ) -exec /usr/bin/sh -c 'if ! /usr/bin/sbverify --list {} 2>/dev/null | /usr/bin/grep -q "signature certificates"; then /usr/bin/sbsign --key db.key --cert db.crt --output "$1" "$1"; fi' _ {} ;
Depends = sbsigntools
Depends = findutils
Depends = grep
EOF

}

install_grub() {

    echo ">>> installing grub bootloader"
    grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id="Arch Linux"

    if grep -q zfs /etc/fstab; then
        sed -i 's|^GRUB_CMDLINE_LINUX=".*"|GRUB_CMDLINE_LINUX=""|' /etc/default/grub
        sed -i 's|^GRUB_PRELOAD_MODULES=".*"|GRUB_PRELOAD_MODULES="usb usb_keyboard part_gpt nvme zfs zfscrypt zfsinfo"|' /etc/default/grub
        echo 'export ZPOOL_VDEV_NAME_PATH=YES' >> /etc/profile.d/zpool_vdev_name_path.sh
        source /etc/profile.d/zpool_vdev_name_path.sh
        echo 'Defaults env_keep += "ZPOOL_VDEV_NAME_PATH"' >> /etc/sudoer
        sed -i "s|rpool=.*|rpool=\`zdb -l \${GRUB_DEVICE} \| grep -E '[[:blank:]]name' \| cut -d\\\' -f 2\`|" /etc/grub.d/10_linux
    else
        sed -i 's|^GRUB_PRELOAD_MODULES=".*"|GRUB_PRELOAD_MODULES="usb usb_keyboard part_gpt nvme"|' /etc/default/grub
    fi

    if [[ -d /boot/grub/themes/starfield ]]; then
        rm -r /boot/grub/themes/starfield
    fi

    if [[ ! -d /boot/grub/themes/grub-theme ]]; then
        echo ">>> cloning grub-theme"
        cd /boot/grub/themes/
        git clone https://github.com/0free/grub-theme.git
        cd /root
    fi

    sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=1/' /etc/default/grub
    sed -i 's/loglevel=3/loglevel=0/' /etc/default/grub
    sed -i 's|#GRUB_BACKGROUND=".*"|GRUB_THEME="/boot/grub/themes/grub-theme/background.png"|' /etc/default/grub
    sed -i 's|#GRUB_THEME=".*"|GRUB_THEME="/boot/grub/themes/grub-theme/theme.txt"|' /etc/default/grub

    sed -i 's|#GRUB_SAVEDEFAULT|GRUB_SAVEDEFAULT|' /etc/default/grub
    sed -i 's|#GRUB_DISABLE_OS_PROBER|GRUB_DISABLE_OS_PROBER|' /etc/default/grub

    echo ">>> making grub config"
    grub-mkconfig -o /boot/grub/grub.cfg

}

firmware_update() {

    echo ">>> updating firmware"
    fwupdmgr get-devices
    fwupdmgr refresh
    fwupdmgr get-updates
    fwupdmgr update

}

set_initcpio() {

    if grep -q btrfs /etc/fstab; then
        MODULES+=(btrfs)
    fi

    if grep -q zfs /etc/fstab; then
        MODULES+=(zfs)
        sed -i 's/filesystems keyboard fsck/keyboard zfs filesystems/' /etc/mkinitcpio.conf
    fi

    MODULES+=(usbhid xhci_hcd)
    MODULES+=(i915 intel_agp)
    MODULES+=(amdgpu)
    MODULES+=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)

    list=''
    for i in ${!MODULES[@]}; do
        list+=${MODULES[$i]}
        list+=' '
    done

    sed -i "s|^MODULES=(.*)|MODULES=($list)|" /etc/mkinitcpio.conf

    echo ">>> building initial ramdisk"
    mkinitcpio --allpresets

}

finish() {

    echo ">>> rebooting"
    exit
    exit
    umount /mnt/boot

    if [[ $filesystem == 'zfs' ]]; then
        zfs umount -a
        zpool export rpool
    elif mountpoint -q /mnt; then
        umount -l /mnt
    fi

    reboot -f

}

clear && set -e

if [[ -f /root/chroot ]]; then
    uuid=$(cat /root/chroot)
    computer=$(cat /root/computer)
    desktop=$(cat /root/desktop)
    aur_installer=$(cat /root/aur)
    bootloader=$(cat /root/bootloader)
    if [ $(find /home -maxdepth 1 -type d | wc -l) -ne 1 ]; then
        USER=$(ls /home)
        if [[ -f /root/desktop ]]; then
            setup_desktop
        else
            if [[ $bootloader == 'grub' ]]; then
                install_grub
            else
                install_bootloader
            fi
        fi
    else
        configure
    fi
else
    if mountpoint -q /mnt; then
        if [[ -f /mnt/etc/fstab ]]; then
            change_root
        else
            install_base
        fi
    else
        setup_drive
    fi
fi

#end
